### PR TITLE
support for self hosted PDS

### PR DESCRIPTION
**Pull request by kodxana**

### CODE REVIEW

**Comment by kawamataryo** [comment]
Thank you for your contribution! I really appreciate the detailed information you provided in the README.

**Review by kawamataryo — APPROVED** [review]

**Comment by xPaw** [comment]
Wouldn't it be better to add this as an extra input in the popup so that users can change it without recompiling the extension locally?

**Comment by kodxana** [comment]
> can

Most issue would come with browser web stores and permissions. As we do not know user domains it would require use to ask user to provide permissions to access all pages.

**Comment by xPaw** [comment]
Right. maybe dynamic/optional goat permission would work for this

**Pull request merged**
