### PR TITLE
[RFC] Allow Users to Import List from Bridge

### LINKED ISSUE #110: [Feature Request] Allow users to create lists from bridge
**Current Problem:**
Currently we allow `Users` to export their `List Members` from Twitter and then run the `Follow All` action on them in Bridge to import them to Bsky. This is good but a lot of `Users` on Twitter use `Lists` to follow `Users` they wouldn't otherwise follow across segmented topics. This may lead to some cumbersome post-import pain points for `Users` looking to remodel their Twitter `Lists` in Bsky.

**Proposed Solution:**
It would be nice if instead we could also import `List Members` as `Lists` from Bridge. We could add a new action `Create List` that allows `Users` to create a new `List` with that batch. We could then even iterate and allow `Users` to add batches of existing `Lists` if we feel good about this.

Curious how we feel about this? Haven't had a chance to do much more than check the Bsky API docs for feasibility but it seems doable, no? I realize this may be expanding the complexity/scope of the project a bit but wanted to float the idea to get the conversation started as a `List Enjoyer` who could personally get some utility from something like this.

### PR DESCRIPTION
**Pull request by dtflowers**
## MVP Implementation of `Import List` Action

This PR is a first pass to fix #110 by implementing an `Import List` action for importing Twitter Lists into Bsky. For a detailed description of the concept, please refer to this issue. 

### Summary

This PR introduces the following changes to implement this feature:

- **New Message for `import_list`**: Added a new message type for `import_list` instead of mirroring the `follow_all` action for lists.
- **New Methods for Bsky Client**: Updated the Bsky client with new methods to create lists and add users to lists.
- **List Title Scraping**: Scraped the list title from the background of the list members page and used browser cache to persist it. This ensures the bridge can pass the list title to Bsky. Added a fallback value to handle cases where the list title is not available in the DOM.
- **UI Update**: Replaced the `follow_all` button with an `import_list` button when run on list members. Users can still follow list members individually from the bridge.
- **Bulk Action Handling**: Running "import list" from the bridge creates a new list with the same name in Bsky and adds all members in bulk. Need to verify Bsky API limits for bulk actions.

### Next Steps

- **Stress Testing**: Ensure the implementation works reliably and does not break existing functionality. (I have tested the follow and block actions on this branch locally and they still work as intended, but please double check me.)
- **Bluesky API Bulk Limits?**: Will need to review the create list endpoint and potentially build in some handling to stay in line of any bulk batch limits on the API. Have not had a chance to see what our upper limits of adding users to a list would be as currently configured.
- **Discussion**: Open to discussing the implementation details here but perhaps there is also a larger discussion to be had about if this is actually the functionality we want?  Is this missing something important? Is there some aspect of this UX that we don't like?  Do we need to add more functionality (like adding members to existing lists or like potentially renaming/custom naming lists from the bridge) for this to be viable or could something like this work as an MVP?

### Video Demo of MVP Functionality
https://github.com/user-attachments/assets/22322257-5f06-4e0e-9a5b-530afda20899

### CODE REVIEW

**Comment by dtflowers** [comment]
Ahh looks like a ran afoul of the linter here, think I might have some different rules in my local config my bad, will get it cleaned up.

**Comment by kawamataryo** [comment]
@dtflowers
This is amazing!! I really appreciate your contribution! I'll test it out tonight!

**Comment by dtflowers** [comment]
I ran it on a few lists earlier and found it worked pretty well fwiw.  

I noticed in testing there are a few cases where X will reload the feed in the background while keeping the list members loading in the modal; we seem to lose the ability to scrape the list title from the DOM when that happens but the import should still succeed with the fallback default title in that case. User can just rename the list on the other side.  I think it's probably fine.

**Comment by kawamataryo** [comment]
I was able to verify the functionality on my end as well, and I don't see any impact on existing features. I think this PR is a great first step towards resolving #110.

Here are a few things I noticed:

**- Hiding the Follow All button:** I think it would be better to keep the Follow All button visible and add the Import List separately. This might also keep the implementation simpler. If there’s not enough space in the sidebar, we could consider moving support links or links to social media.
**- Displaying a link to the created list:** After the Import List is completed, I’d like to display a link to Bluesky as part of the interaction. It would be nice to show a completion message along with the link in a modal or something similar.
**- Indicating that this is an experimental feature:** Since there are limitations with the Bluesky API and other UI constraints (like not being able to exclude users individually), it should be clearly indicated that this is an experimental feature. It could be noted below the Import List button and in a confirmation message before execution.

I think addressing these points can wait until after we've merged this PR. Thank you again for an excellent MVP.

**Comment by dtflowers** [comment]
Yeah those both make sense. I'll take a look and get that sorted when I have some time, if not tonight, hopefully tomorrow!

**Comment by kawamataryo** [comment]
I added [react-toastify](https://fkhadra.github.io/react-toastify/introduction) to the main branch. It would be helpful to use this to show a link to the list once the import is complete.

**Comment by kawamataryo** [comment]
@dtflowers, how have you been since then? If you're busy, I might go ahead and merge this PR, making any additional fixes myself. In any case, I really appreciate your contributions. Thank you!

**Comment by fadookie** [comment]
Thanks! I'm interested in using this feature, how can I find out when it goes live in the chrome web store?

**Comment by kawamataryo** [comment]
@fadookie 
I plan to apply to the web store today! If all goes well, it should be available by tomorrow or the day after.

**Pull request merged**
