### PR TITLE
Only search unique terms

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by xPaw** [comment]
Also I think there's a bug that it keeps looping the search even after reaching the bottom. I had service worker open on network tab, and it keeps sending searches over and over.

**Review by kawamataryo — APPROVED** [review]
Absolutely! Thank you for your contribution!

**Comment by kawamataryo** [comment]
@xPaw 
I'll also look into the bug where it keeps searching even after reaching the bottom! Thank you.

**Comment by kawamataryo** [comment]
I fixed the loop bug in this commit. It will be released in v1.0.8. Thank you for your contribution!

**Pull request merged**
