### PR TITLE
Add separate handling for list members modal scrolling

### LINKED ISSUE #83: Lists not loading properly
When I load one of my list's members, using the "x.com/i/lists/<list_id>/members" url, or by going to the list, clicking Manage, clicking Members, or by just clicking "Manage Members" from the list's page, the Bridge app will load the first page just fine, but then it will start scrolling the background Twitter/X page, and *not* the List in the foreground of the window, which is causing the App to load users that are being reshared onto that timeline, and not the people that have been added to the list.  Restarting Chrome, updating the Bridge app, and restarting my computer do not fix this issue.  This occurs with all lists I attempt.

### PR DESCRIPTION
**Pull request by dtflowers**
Fixes #83 

Hopefully this is at least a good start to get us cleaned up here and not too messy, but open to any suggestion on how to clean this up to make it less convoluted.

The issue is that we currently scroll in this hook by referencing the window. This works fine for the followers and block lists but it doesn't work for the way twitter displays the members of lists in a modal. If we run this on a list, we should instead reference the viewport container of the modal and then use its initial height to scroll through it to fetch more list members.

I have tested this locally against list modals, followers list, and block list but please let me know if I've broken any edge cases.

### CODE REVIEW

**Comment by kawamataryo** [comment]
Thank you for your contribution! It looks good.
I'll test it in my environment as well.

**Review by kawamataryo — APPROVED** [review]
It worked perfectly! Thank you!

**Comment by kawamataryo** [comment]
It is scheduled to be released in version 1.0.7.

**Comment by mezz** [comment]
Hello, I ran into this issue and I am happy to see that it is fixed!
Sorry but I am not able to find version 1.0.7, is it available to try?
Thank you for your work on this plugin.

**Comment by kawamataryo** [comment]
V1.0.7 is currently under review in the Chrome web store!

**Comment by kawamataryo** [comment]
Version 1.0.7 has been released on the Chrome Store!

**Comment by mezz** [comment]
Thank you! It is working correctly again.

**Pull request merged**
